## CREATE LOCAL APP

## CREATE API CALLS

## IMPORT INITIAL DATA FILE AND CONVERT TO DATAFRAME

## CREATE SCORING ALGORITHM

## UPDATE DATAFRAME FOR SCORING CALCULATIONS AND SORT

## RETURN HUMAN READABLE ITINERARY